PN-4637:Script log errors extractor
pagopa/pn-infra pull request #170
Opened 2023-03-09 17:43 UTC by mbrachi

script estrazione log aws

2023-03-10 08:04 UTC, fdammassa requested changes

2023-03-10 08:04 UTC, fdammassa commented on scripts/log-errors-extractor/log_error_extractor.sh
> +aws ${aws_command_base_args} logs start-query  --log-group-name $loggrlb  --start-time `date -j -v-1H +%s000` --end-time `date +%s000`  --query-string "${searchquery}"  | awk '{print $2}' | cut -d "\
@mbrachi la searchquery della lambda deve essere per forza di cose diversa, devi cercare "ERROR" dentro message

2023-03-10 08:04 UTC, fdammassa commented on scripts/log-errors-extractor/log_error_extractor.sh
> +sed -i '' 's/result//g' report.txt && sed -i '' 's/_/\//g' report.txt  && sed -i ''  's/\.txt//g' report.txt
@mbrachi il conteggio delle righe alla fine era corretto?

2023-03-10 10:52 UTC, mbrachi commented on scripts/log-errors-extractor/log_error_extractor.sh
> +aws ${aws_command_base_args} logs start-query  --log-group-name $loggrlb  --start-time `date -j -v-1H +%s000` --end-time `date +%s000`  --query-string "${searchquery}"  | awk '{print $2}' | cut -d "\
fixata e gestita tramite variabile con una sed

2023-03-10 10:53 UTC, mbrachi commented on scripts/log-errors-extractor/log_error_extractor.sh
> +sed -i '' 's/result//g' report.txt && sed -i '' 's/_/\//g' report.txt  && sed -i ''  's/\.txt//g' report.txt
si, ho controllato per il log group di pn-delivery-push sia su CW sia l'outuput dello script e le numeriche coincidono.
Inoltre ho controllato il conteggio delle stringhe sull'output dello script e sono corrette.

2023-03-13 13:29 UTC, fdammassa approved these changes

2023-03-13 13:40 UTC, merged