Hotfix/pn 2722 b
pagopa/pn-infra pull request #75
Opened 2022-11-23 10:54 UTC by fdammassa

TLS connection on Network Load Balancer

2022-11-23 11:10 UTC, marco-vit-pagopa requested changes
Potresti aggiornare anche il manuale operativo descrivendo i parametri in più che sono richiesti per il deploy di infra.

2022-11-23 11:25 UTC, fdammassa commented
@marco-vit-pagopa Ho aggiornato la guida!

2022-11-23 14:03 UTC, marco-vit-pagopa approved these changes

2022-11-23 14:57 UTC, MTurraPpa approved these changes

2022-11-24 09:43 UTC, MTurraPpa reviewed
Non è meglio cercare nei log iun=,uid=, etc

Vedi https://pagopa.atlassian.net/wiki/spaces/PN/pages/449151059/Logging+Standards#How-to-write-data-in-message

2022-11-24 09:44 UTC, MTurraPpa reviewed
PS: non mi sembra che queste modifiche abbiano a che fare con la PN-2617 del commit

2022-11-24 10:07 UTC, fdammassa commented
@MTurraPpa 
- aggiornata descrizione task https://pagopa.atlassian.net/browse/PN-2722 
- aggiornata aggiornata regex per iun

2022-11-25 16:42 UTC, merged